version: "3.9"

services:
  ifoodapp:
    container_name: ifoodapp
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}