version: "3.9"

services:
  ifoodapp:
    container_name: ifoodapp
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - DB_DRIVER=django.db.backends.postgresql
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=127.0.0.1
      - TZ=America/Sao_Paulo

volumes:
  pgdata: {}