version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432" # Ajuste a porta aqui para corresponder à porta padrão do PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ifood-network # Adicione a rede aqui

  ifoodapp:
    container_name: ifoodapp
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db
    networks:
      - ifood-network # Adicione a rede aqui

networks: # Defina a rede aqui
  ifood-network:
    driver: bridge

volumes:
  pgdata: {}
